/**
 * OpenAI Agent configuration and message processing.
 *
 * Creates an Agent with web search and wave-read tools, then
 * exposes a processMessage() function that runs the agent within
 * the per-wave session.
 */

import { Agent, run } from '@openai/agents';
import { z } from 'zod';
import { webSearch } from './tools/web-search.js';
import { createWaveReadTool } from './tools/wave-read.js';
import { createImageGenTool } from './tools/image-gen.js';
import { getSession } from './context.js';
import { WaveClient } from './wave-client.js';
import { sanitizeLlmResponse } from './sanitize-response.js';

/**
 * Structured output schema for the bot's reply decision.
 *
 * The LLM returns this object so the bot can decide whether to post at all.
 */
const BotDecision = z.object({
  shouldReply: z.boolean().describe('Whether the bot should post a reply'),
  response: z
    .string()
    .nullable()
    .describe('The reply text when shouldReply is true; null when shouldReply is false'),
});
export type BotDecision = z.infer<typeof BotDecision>;

/** Image pending insertion after the reply blip is created. */
export interface PendingImage {
  attachmentId: string;
  caption: string;
}

/** Context passed to tools via RunContext. */
export interface WaveContext {
  waveId: string;
  /** Images generated by the generate_image tool, to be inserted after reply. */
  pendingImages?: PendingImage[];
}

const BOT_NAME = (process.env['ROBOT_ADDRESS'] ?? 'gpt-ts-bot@supawave.ai').split('@')[0];

const SYSTEM_PROMPT = `You are ${BOT_NAME}, a helpful AI assistant inside SupaWave — a collaborative real-time editor inspired by Google Wave.

## Reply Decision

You MUST decide whether to reply at all. Return a JSON object with shouldReply and response.

**Always reply (shouldReply: true) when:**
- You are directly @-mentioned (the message contains "@${BOT_NAME}")
- A user is clearly asking you a question or requesting help
- You are the only other participant in the conversation
- This is the first message in a wave you just joined

**Stay silent (shouldReply: false, response: null) when:**
- A user has told you to stop responding, shut up, be quiet, go away, or only reply when mentioned
- The message is clearly directed at another user, not you
- It is a multi-user conversation and people are talking to each other without involving you
- The message is a simple acknowledgment (e.g. "ok", "thanks", "got it") not directed at you

**Important:** If a user previously told you to be quiet or only reply when mentioned, you MUST remember that instruction and stay silent on subsequent messages unless you are directly @-mentioned. The @-mention override is absolute — always reply when @-mentioned, regardless of prior "shut up" instructions.

## Response Formatting

CRITICAL: Always respond in **Markdown format**. Use **bold** for emphasis, "- " bullet lists for enumerations, [link text](url) for references, and ## Heading for section headers. Separate every paragraph, list item, and section with a newline. Use blank lines between sections.

Rules:
- Use Markdown syntax throughout — the Wave client renders it natively
- Use line breaks (newlines) between paragraphs and sections
- Use "- " for bullet points, each on its own line
- Use **bold** for emphasis
- Use [link text](url) for hyperlinks — never paste bare URLs
- Use numbered lists with each item on its own line
- Keep responses concise and well-structured
- Do NOT put everything on one line
- **Images:** You can generate images using the \`generate_image\` tool. When a user asks you to create, draw, or visualize something, use it. The image will appear inline in the wave blip. For external image references, use a plain hyperlink: \`[View image](url)\` — do NOT use \`![alt](url)\` markdown syntax
- **Tables:** You may use Markdown pipe tables for structured data. Keep tables simple (a few columns). The Wave client renders table cells as plain text separated by │

Example of GOOD formatting:
Here is the answer to your question.

**Key points:**
- First point explained clearly
- Second point with details
- Third point

Let me know if you need more details.

Example of BAD formatting (DO NOT DO THIS):
Here is the answer. **Key points:** - First point - Second point - Third point. Let me know if you need more details.

## Conversation Guidelines

- You are participating in a wave conversation with other users
- You have access to web search — use it for current events or facts you're unsure about
- You can read the full wave conversation using the read_wave tool for more context
- Each wave is a separate conversation. You maintain context within each wave
- Do not repeat previous messages. Focus on the latest user message
- If multiple users are in the wave, address them naturally

## Wave Thread Context

When a message contains a \`<wave-context>\` block, the user created an **inline reply** thread attached to a specific blip in the wave. The content inside \`<wave-context>…</wave-context>\` is the parent blip's content (up to 2000 characters).

- Focus your answer on the **parent blip content**, not the whole conversation
- A short question like "tell me more about this" or "explain this" means: explain the specific content shown in the context block
- If the context is a table row (e.g. "Israel – Iran | Ongoing proxy conflict"), address that row specifically — do not summarize the whole table
- If the context is a paragraph or a claim, address that specific item
- You may still use web search or read_wave for additional details, but anchor your answer to the contextual blip`;

let agent: Agent<WaveContext, typeof BotDecision> | null = null;

/** Lazily initialize the agent (needs WaveClient for tools). */
function getAgent(waveClient: WaveClient): Agent<WaveContext, typeof BotDecision> {
  if (agent) return agent;

  agent = new Agent<WaveContext, typeof BotDecision>({
    name: BOT_NAME,
    instructions: SYSTEM_PROMPT,
    tools: [webSearch, createWaveReadTool(waveClient), createImageGenTool(waveClient)],
    outputType: BotDecision,
  });

  return agent;
}

export interface ProcessMessageOptions {
  waveId: string;
  userMessage: string;
  author: string;
  waveClient: WaveClient;
  /** Content of the parent blip this message is replying to (inline thread). */
  parentContext?: string;
}

/** Result from processMessage including the bot's decision and any generated images. */
export interface ProcessResult {
  decision: BotDecision;
  /** Images generated during the agent run, to be inserted into the reply blip. */
  pendingImages: PendingImage[];
}

/**
 * Process a user message through the agent and return a structured decision.
 * The decision includes whether the bot should reply and the reply text.
 * Uses per-wave sessions for conversation memory.
 */
export async function processMessage({
  waveId,
  userMessage,
  author,
  waveClient,
  parentContext,
}: ProcessMessageOptions): Promise<ProcessResult> {
  const a = getAgent(waveClient);
  const session = getSession(waveId);

  // When the user's blip is an inline reply to another blip, include the
  // parent blip's content in a structured block so the model can answer in
  // context.  XML-style tags avoid the ambiguity that `---` delimiters cause
  // when the parent content itself contains Markdown horizontal rules.
  // Parentcontext is capped to avoid inflating the prompt on large blips.
  const MAX_PARENT_CHARS = 2000;
  const input = parentContext
    ? (() => {
        // Escape any closing-tag variants in the parent content so they cannot
        // break the <wave-context> delimiter. The regex covers optional
        // internal whitespace (e.g. </wave-context >) in addition to the
        // canonical form.
        const safeContext = parentContext
          .slice(0, MAX_PARENT_CHARS)
          .replace(/<\/\s*wave-context\s*>/gi, '[/wave-context]');
        const truncationNote = parentContext.length > MAX_PARENT_CHARS ? '\n[…truncated]' : '';
        return `<wave-context>\n${safeContext}${truncationNote}\n</wave-context>\n[${author}]: ${userMessage}`;
      })()
    : `[${author}]: ${userMessage}`;

  const context: WaveContext = { waveId, pendingImages: [] };
  const result = await run(a, input, {
    session,
    maxTurns: 10,
    context,
  });

  if (result.finalOutput) {
    const decision = result.finalOutput;
    // Strip citation markers and normalize whitespace before the response
    // reaches the Wave UI. OpenAI web-search injects inline source references
    // like 【turn0finance0】 that render as garbled text in Wave blips.
    // Use an explicit null check so we also sanitize empty strings.
    if (decision.response !== null) {
      // Debug-only telemetry for citation artifacts — gated behind
      // DEBUG_CITATION_SANITIZER=1 to avoid logging raw model content.
      if (process.env['DEBUG_CITATION_SANITIZER'] === '1') {
        const hasCitationArtifact =
          /【(?:cite†?)?turn\d+[^】\n]*】/i.test(decision.response) ||
          /\.?citeturn\d+[-a-z0-9†]*/i.test(decision.response);
        if (hasCitationArtifact) {
          console.debug('[agent] citation artifacts detected', {
            responseLength: decision.response.length,
          });
        }
      }
      const sanitized = sanitizeLlmResponse(decision.response);
      // If sanitization reduces the response to an empty string (e.g. the
      // model returned only citation markers), fall back to a safe message
      // so the bot never posts a blank reply.
      decision.response = sanitized || 'I had trouble generating a response. Please try again.';
    }
    return { decision, pendingImages: context.pendingImages ?? [] };
  }

  // Fallback: if the agent didn't produce structured output, reply anyway
  return {
    decision: { shouldReply: true, response: 'I had trouble generating a response. Please try again.' },
    pendingImages: context.pendingImages ?? [],
  };
}
